
// This file has been generated by the GUI designer. Do not modify.
namespace LolcodeInterpreter
{
	public partial class InputPromptDialog
	{
		private global::Gtk.Entry inputEntry;
		
		private global::Gtk.Button okButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LolcodeInterpreter.InputPromptDialog
			this.Name = "LolcodeInterpreter.InputPromptDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child LolcodeInterpreter.InputPromptDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.inputEntry = new global::Gtk.Entry ();
			this.inputEntry.CanFocus = true;
			this.inputEntry.Name = "inputEntry";
			this.inputEntry.IsEditable = true;
			this.inputEntry.ActivatesDefault = true;
			this.inputEntry.InvisibleChar = '•';
			w1.Add (this.inputEntry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1 [this.inputEntry]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Internal child LolcodeInterpreter.InputPromptDialog.ActionArea
			global::Gtk.HButtonBox w3 = this.ActionArea;
			w3.Name = "dialog1_ActionArea";
			w3.Spacing = 10;
			w3.BorderWidth = ((uint)(5));
			w3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.okButton = new global::Gtk.Button ();
			this.okButton.CanDefault = true;
			this.okButton.CanFocus = true;
			this.okButton.Name = "okButton";
			this.okButton.UseStock = true;
			this.okButton.UseUnderline = true;
			this.okButton.Label = "gtk-ok";
			this.AddActionWidget (this.okButton, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w3 [this.okButton]));
			w4.Expand = false;
			w4.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 446;
			this.DefaultHeight = 82;
			this.Show ();
			this.okButton.Clicked += new global::System.EventHandler (this.okButtonOnClick);
		}
	}
}
