
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixedContainer;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView editorTextView;
	
	private global::Gtk.FileChooserButton fileChooser;
	
	private global::Gtk.Button executeButton;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow3;
	
	private global::Gtk.TextView consoleTextView;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TreeView tokenTreeView;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	
	private global::Gtk.TreeView symbolTableTreeView;
	
	private global::Gtk.Label uhm;
	
	private global::Gtk.Label label2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("KTHXBYE124 Lolterpreter No to Finals <3");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixedContainer = new global::Gtk.Fixed ();
		this.fixedContainer.Name = "fixedContainer";
		this.fixedContainer.HasWindow = false;
		// Container child fixedContainer.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.editorTextView = new global::Gtk.TextView ();
		this.editorTextView.WidthRequest = 730;
		this.editorTextView.HeightRequest = 437;
		this.editorTextView.CanFocus = true;
		this.editorTextView.Name = "editorTextView";
		this.GtkScrolledWindow.Add (this.editorTextView);
		this.fixedContainer.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixedContainer [this.GtkScrolledWindow]));
		w2.X = 19;
		w2.Y = 52;
		// Container child fixedContainer.Gtk.Fixed+FixedChild
		this.fileChooser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.fileChooser.WidthRequest = 150;
		this.fileChooser.Name = "fileChooser";
		this.fixedContainer.Add (this.fileChooser);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixedContainer [this.fileChooser]));
		w3.X = 25;
		w3.Y = 12;
		// Container child fixedContainer.Gtk.Fixed+FixedChild
		this.executeButton = new global::Gtk.Button ();
		this.executeButton.CanFocus = true;
		this.executeButton.Name = "executeButton";
		this.executeButton.UseUnderline = true;
		this.executeButton.Label = global::Mono.Unix.Catalog.GetString ("Execute");
		this.fixedContainer.Add (this.executeButton);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixedContainer [this.executeButton]));
		w4.X = 181;
		w4.Y = 13;
		// Container child fixedContainer.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.consoleTextView = new global::Gtk.TextView ();
		this.consoleTextView.WidthRequest = 1100;
		this.consoleTextView.HeightRequest = 230;
		this.consoleTextView.CanFocus = true;
		this.consoleTextView.Name = "consoleTextView";
		this.consoleTextView.Editable = false;
		this.GtkScrolledWindow3.Add (this.consoleTextView);
		this.fixedContainer.Add (this.GtkScrolledWindow3);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixedContainer [this.GtkScrolledWindow3]));
		w6.X = 18;
		w6.Y = 501;
		// Container child fixedContainer.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.tokenTreeView = new global::Gtk.TreeView ();
		this.tokenTreeView.WidthRequest = 350;
		this.tokenTreeView.HeightRequest = 207;
		this.tokenTreeView.CanFocus = true;
		this.tokenTreeView.Name = "tokenTreeView";
		this.GtkScrolledWindow1.Add (this.tokenTreeView);
		this.fixedContainer.Add (this.GtkScrolledWindow1);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixedContainer [this.GtkScrolledWindow1]));
		w8.X = 765;
		w8.Y = 51;
		// Container child fixedContainer.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.symbolTableTreeView = new global::Gtk.TreeView ();
		this.symbolTableTreeView.WidthRequest = 350;
		this.symbolTableTreeView.HeightRequest = 200;
		this.symbolTableTreeView.CanFocus = true;
		this.symbolTableTreeView.Name = "symbolTableTreeView";
		this.GtkScrolledWindow2.Add (this.symbolTableTreeView);
		this.fixedContainer.Add (this.GtkScrolledWindow2);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixedContainer [this.GtkScrolledWindow2]));
		w10.X = 766;
		w10.Y = 288;
		// Container child fixedContainer.Gtk.Fixed+FixedChild
		this.uhm = new global::Gtk.Label ();
		this.uhm.Name = "uhm";
		this.uhm.LabelProp = global::Mono.Unix.Catalog.GetString ("Symbol Table");
		this.fixedContainer.Add (this.uhm);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixedContainer [this.uhm]));
		w11.X = 770;
		w11.Y = 268;
		// Container child fixedContainer.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Tokens");
		this.fixedContainer.Add (this.label2);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixedContainer [this.label2]));
		w12.X = 770;
		w12.Y = 31;
		this.Add (this.fixedContainer);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1133;
		this.DefaultHeight = 756;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.fileChooser.SelectionChanged += new global::System.EventHandler (this.transferSourceCodeToEditor);
		this.executeButton.Clicked += new global::System.EventHandler (this.onExecuteButtonClick);
	}
}
